### ISSUE TITLE
Pip version is outdated

### ISSUE THREAD

**Issue by AdamIsrael** [madprime/python-gedcom#9]
Hi there!

The version of python-gedcom in pip is outdated (it doesn't have the python3 fixes). Could a new version be uploaded?

Thanks!

**Comment by nickreynke** [comment]
Hey @AdamIsrael :) Have you took a look at the new repository? There is an updated version which is also on Pip :)

**Comment by AdamIsrael** [comment]
Hey @nickreynke. I hadn't, but I see the new repo now so I'll take a look. Very good timing. :)
